"""add cleared_at to roommember

Revision ID: bcee0a28fd80
Revises: beae30a734dd
Create Date: 2026-02-28 20:38:46.375531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcee0a28fd80'
down_revision: Union[str, Sequence[str], None] = 'beae30a734dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_members', 'cleared_at')
    # ### end Alembic commands ###
