"""add_is_edited_is_deleted_to_messages

Revision ID: beae30a734dd
Revises: 004
Create Date: 2026-02-26 08:06:24.313379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beae30a734dd'
down_revision: Union[str, Sequence[str], None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'github_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'is_edited')
    # ### end Alembic commands ###
