"""add reply_to_id to message

Revision ID: c607dda928fb
Revises: bcee0a28fd80
Create Date: 2026-02-28 20:52:54.892038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c607dda928fb'
down_revision: Union[str, Sequence[str], None] = 'bcee0a28fd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_id')
    # ### end Alembic commands ###
